name: Deploy Peaxel Bot

on:
  push:
    branches: [main, master] # On couvre les deux noms de branche possibles

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pre-check Secrets
        run: |
          if [ -z "${{ secrets.SSH_HOST }}" ]; then echo "❌ SSH_HOST is EMPTY"; exit 1; fi
          if [ -z "${{ secrets.SSH_USER }}" ]; then echo "❌ SSH_USER is EMPTY"; exit 1; fi
          echo "✅ Secrets are detected by GitHub"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/peaxel-bot
            git pull origin ${{ github.ref_name }}
            source ~/nodevenv/peaxel-bot/20/bin/activate
            npm install --production
            touch tmp/restart.txt
