name: Deploy Peaxel Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ðŸšš Transfert des fichiers (SFTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: oafw0766.odns.fr
          username: oafw0766
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22
          local-dir: ./
          # VÃ©rifie dans ton gestionnaire de fichiers si c'est 'peaxel-bot' ou 'peaxel'
          server-dir: ./peaxel-bot/ 
          exclude: |
            **/.git*
            **/node_modules/**
            **/.github/**

      - name: ðŸ”„ RedÃ©marrage du Bot
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true # Ã‰vite de marquer le dÃ©ploiement en rouge si le pare-feu bloque
        with:
          host: oafw0766.odns.fr
          username: oafw0766
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 10s
          script: |
            cd /home/oafw0766/peaxel-bot
            source /home/oafw0766/nodevenv/peaxel-bot/20/bin/activate
            npm install --production
            touch tmp/restart.txt