name: Deploy Peaxel Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ðŸšš Transfert des fichiers
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: oafw0766.odns.fr
          username: oafw0766
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./peaxel-bot/ 
          exclude: |
            **/.git*
            **/.git/**
            **/node_modules/**
            **/.github/**
            .env
            .gitignore
            README.md

      - name: ðŸ”„ Tentative de redÃ©marrage
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: oafw0766.odns.fr
          username: oafw0766
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 15s
          script: |
            cd /home/oafw0766/peaxel-bot
            source /home/oafw0766/nodevenv/peaxel-bot/20/bin/activate
            npm install --production
            touch tmp/restart.txt